[package]
name = "roomba_port"
version = "0.1.0"
authors = ["Matthew Philyaw <matthew.philyaw@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.14"
log = "0.3.1"
env_logger = "0.3.0"
serial = "0.0.5"
time = "0.1"
